export default {
    EXPAND: 'EXPAND',
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    OPEN_SUCCESS_MODAL: 'OPEN_SUCCESS_MODAL',
    CLOSE_SUCCESS_MODAL: 'CLOSE_SUCCESS_MODAL',
    OPEN_ERROR_MODAL: 'OPEN_ERROR_MODAL',
    CLOSE_ERROR_MODAL: 'CLOSE_ERROR_MODAL',
    LOADING: 'LOADING'
}